import { defineField, defineType } from "sanity";
import { projectMarkets } from "@/lib/projectMarkets";

export const project = defineType({
  name: "project",
  title: "PROJECTS - Project",
  type: "document",
  description: "Satu project untuk listing Projects, highlight Home, dan halaman detail project.",
  fieldsets: [
    { name: "archive", title: "Archive and listing", options: { collapsible: true, collapsed: false } },
    { name: "story", title: "Project story", options: { collapsible: true, collapsed: false } },
    { name: "media", title: "Images and media", options: { collapsible: true, collapsed: false } },
    { name: "people", title: "Project team", options: { collapsible: true, collapsed: true } },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Project title",
      type: "string",
      description: "Single project title. Write in the preferred editorial language.",
      validation: (Rule) => Rule.required(),
      fieldset: "archive",
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      options: {
        source: "title",
        maxLength: 96,
      },
      validation: (Rule) => Rule.required(),
      fieldset: "archive",
    }),
    defineField({
      name: "coverImage",
      title: "Cover image",
      type: "image",
      options: { hotspot: true },
      description: "Primary image for the project listing and detail page hero.",
      validation: (Rule) => Rule.required(),
      fieldset: "media",
    }),
    defineField({
      name: "gallery",
      title: "Gallery",
      type: "array",
      of: [{ type: "image", options: { hotspot: true } }],
      description: "Additional project photos for the story narrative.",
      fieldset: "media",
    }),
    defineField({
      name: "category",
      title: "Category",
      type: "string",
      options: {
        list: [
          { title: "Architecture", value: "Architecture" },
          { title: "Design", value: "Design" },
        ],
        layout: "radio",
      },
      description: "Choose one primary archive category for the project.",
      fieldset: "archive",
    }),
    defineField({
      name: "status",
      title: "Status",
      type: "string",
      description: "Free-text project status. Use Ongoing for current work; blank values are treated as completed.",
      fieldset: "archive",
    }),
    defineField({
      name: "market",
      title: "Market",
      type: "string",
      options: {
        list: projectMarkets.map((market) => ({ title: market, value: market })),
        layout: "radio",
      },
      description: "Sector this project serves. Use Hospitality, Residential, Commercial, or Workplace. This is separate from the project's design style.",
      fieldset: "archive",
    }),
    defineField({
      name: "styleTag",
      title: "Style",
      type: "string",
      description: "Design character or visual language, for example Modern Tropical, American Classic, Adaptive Reuse, or Culture.",
      fieldset: "archive",
    }),
    defineField({
      name: "homeTagline",
      title: "Home highlight tagline",
      type: "string",
      description: "Short supporting line shown under this project when it appears in the Home highlights.",
      fieldset: "archive",
    }),
    defineField({
      name: "location",
      title: "Location",
      type: "string",
      description: "Project location.",
      fieldset: "archive",
    }),
    defineField({
      name: "year",
      title: "Year",
      type: "string",
      description: "Project completion year or period.",
      fieldset: "archive",
    }),
    defineField({
      name: "area",
      title: "Area",
      type: "string",
      description: "Project size such as 120 m².",
      fieldset: "archive",
    }),
    defineField({
      name: "description",
      title: "Description",
      type: "array",
      of: [{ type: "block" }],
      description: "Narrative description for the concept/design story.",
      fieldset: "story",
    }),
    defineField({
      name: "atAGlance",
      title: "At a glance",
      type: "array",
      of: [{ type: "block" }],
      description: "Short editorial introduction shown before the project data.",
      fieldset: "story",
    }),
    defineField({
      name: "editorialSections",
      title: "Editorial sections",
      type: "array",
      of: [{
        type: "object",
        fields: [
          defineField({ name: "label", title: "Section label", type: "string" }),
          defineField({ name: "heading", title: "Heading", type: "string" }),
          defineField({ name: "body", title: "Body", type: "array", of: [{ type: "block" }] }),
          defineField({ name: "image", title: "Section image", type: "image", options: { hotspot: true } }),
        ],
        preview: { select: { title: "heading", subtitle: "label", media: "image" } },
      }],
      description: "Flexible story sections. Each project can have different sections.",
      fieldset: "story",
    }),
    defineField({
      name: "quote",
      title: "Quote",
      type: "text",
      rows: 4,
      description: "Optional statement to feature in the project story.",
      fieldset: "story",
    }),
    defineField({
      name: "quoteAuthor",
      title: "Quote author",
      type: "string",
      fieldset: "story",
    }),
    defineField({
      name: "scopeOfWork",
      title: "Scope of work",
      type: "string",
      description: "Optional summary of scope.",
      fieldset: "archive",
    }),
    defineField({
      name: "team",
      title: "Project team",
      type: "array",
      of: [{
        type: "object",
        fields: [
          defineField({ name: "role", title: "Role", type: "string", validation: (Rule) => Rule.required() }),
          defineField({ name: "members", title: "Members", type: "array", of: [{ type: "string" }], validation: (Rule) => Rule.min(1) }),
        ],
        preview: {
          select: { title: "role" },
        },
      }],
      description: "People or companies involved in this project, grouped by role.",
      fieldset: "people",
    }),
    defineField({
      name: "featured",
      title: "Featured on home",
      type: "boolean",
      initialValue: false,
      fieldset: "archive",
    }),
    defineField({
      name: "order",
      title: "Display order",
      type: "number",
      description: "Used to define listing and next/previous project browsing order.",
      fieldset: "archive",
    }),
  ],
  preview: {
    select: {
      title: "title",
      media: "coverImage",
    },
  },
});
