import { defineField, defineType } from "sanity";

export const siteSettings = defineType({
  name: "siteSettings",
  title: "Site settings",
  type: "document",
  fieldsets: [
    {
      name: "homeContent",
      title: "HOME - Text and project highlights",
      description: "Edit the Home highlight label, heading, empty state, and project discovery link. Choose the projects themselves in Home > Project highlights.",
    },
    {
      name: "aboutContent",
      title: "ABOUT - Page text and sections",
      description: "Edit the About introduction, principles, vision, mission, process, section labels, and closing CTA.",
    },
    {
      name: "servicesContent",
      title: "SERVICES - Page text, process, and images",
      description: "Edit the Services introduction, process text, process stages, and the project images shown on the Services page.",
    },
    {
      name: "studioVisual",
      title: "ABOUT - Studio visual",
      description: "Edit the studio image or video shown on About and on related project pages. Video is used first when both are filled.",
    },
    {
      name: "globalBrand",
      title: "GLOBAL - Brand identity",
      description: "Site-wide identity used by the header and footer.",
    },
    {
      name: "globalContact",
      title: "GLOBAL - Contact details",
      description: "The address, Maps link, and WhatsApp details used by Contact, footer, and inquiry buttons.",
    },
    {
      name: "globalFooter",
      title: "GLOBAL - Footer and social links",
      description: "Footer brand text and social media destinations.",
    },
    {
      name: "globalSeo",
      title: "GLOBAL - SEO defaults",
      description: "Default page title and description used when a page has no more specific SEO content.",
    },
  ],
  fields: [
    defineField({
      name: "logo",
      title: "Logo used across the website",
      type: "image",
      options: { hotspot: true },
      fieldset: "globalBrand",
    }),
    defineField({
      name: "projectHighlightImages",
      title: "Services project highlight images",
      type: "array",
      of: [{ type: "image", options: { hotspot: true } }],
      validation: (Rule) => Rule.max(4),
      description: "Opsional. Gambar carousel project pada halaman Services. Maksimal 4 gambar.",
      fieldset: "servicesContent",
    }),
    defineField({
      name: "homeHighlightsLabel",
      title: "Home highlight label",
      type: "string",
      fieldset: "homeContent",
    }),
    defineField({
      name: "homeHighlightsTitle",
      title: "Home highlight heading",
      type: "string",
      fieldset: "homeContent",
    }),
    defineField({
      name: "homeHighlightsEmpty",
      title: "Home empty-state message",
      type: "text",
      rows: 2,
      fieldset: "homeContent",
    }),
    defineField({
      name: "homeDiscoverLabel",
      title: "Home project link label",
      type: "string",
      fieldset: "homeContent",
    }),
    defineField({
      name: "brandStatement",
      title: "Footer brand statement",
      type: "string",
      fieldset: "globalFooter",
    }),
    defineField({
      name: "aboutEstablished",
      title: "ABOUT - Tagline established",
      type: "string",
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutDescription",
      title: "ABOUT - Deskripsi studio",
      type: "text",
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutKey",
      title: "ABOUT - Kata kunci studio",
      type: "array",
      of: [{
        type: "object",
        fields: [
          defineField({ name: "label", title: "Keyword", type: "string" }),
          defineField({ name: "order", title: "Display order", type: "number" }),
        ],
      }],
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutPrinciplesIntro",
      title: "ABOUT - Intro principles",
      type: "text",
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutPrinciplesContext",
      title: "ABOUT - Catatan context principles",
      type: "text",
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutPrinciples",
      title: "ABOUT - Daftar principles",
      type: "array",
      of: [{
        type: "object",
        fields: [
          defineField({ name: "title", title: "Title", type: "string" }),
          defineField({ name: "description", title: "Description", type: "text" }),
          defineField({ name: "image", title: "Image", type: "image", options: { hotspot: true } }),
          defineField({ name: "order", title: "Display order", type: "number" }),
        ],
      }],
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutVision",
      title: "ABOUT - Teks vision",
      type: "text",
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutVisionSupport",
      title: "ABOUT - Teks pendukung vision",
      type: "text",
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutVisionImage",
      title: "ABOUT - Gambar vision",
      type: "image",
      options: { hotspot: true },
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutMission",
      title: "ABOUT - Mission points",
      type: "array",
      of: [{ type: "text" }],
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutMissionLead",
      title: "ABOUT - Mission lead",
      type: "text",
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutMissionSupport",
      title: "ABOUT - Teks pendukung mission",
      type: "text",
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutMissionDetails",
      title: "ABOUT - Detail mission",
      type: "array",
      of: [{
        type: "object",
        fields: [
          defineField({ name: "label", title: "Label", type: "string" }),
          defineField({ name: "description", title: "Description", type: "text" }),
          defineField({ name: "order", title: "Display order", type: "number" }),
        ],
      }],
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutMissionImage",
      title: "ABOUT - Gambar mission",
      type: "image",
      options: { hotspot: true },
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutProcess",
      title: "ABOUT - Tahapan process",
      type: "array",
      of: [{
        type: "object",
        fields: [
          defineField({ name: "title", title: "Stage title", type: "string" }),
          defineField({ name: "subtitle", title: "Stage subtitle", type: "string" }),
          defineField({ name: "description", title: "Stage description", type: "text" }),
          defineField({ name: "image", title: "Stage image", type: "image", options: { hotspot: true } }),
          defineField({ name: "order", title: "Display order", type: "number" }),
        ],
      }],
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutPageLabel",
      title: "About page eyebrow label",
      type: "string",
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutPrinciplesLabel",
      title: "About principles label",
      type: "string",
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutVisionLabel",
      title: "About vision label",
      type: "string",
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutMissionLabel",
      title: "About mission label",
      type: "string",
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutProcessLabel",
      title: "About process label",
      type: "string",
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutPrinciplesAside",
      title: "About principles aside label",
      type: "string",
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutVisionAside",
      title: "About vision aside label",
      type: "string",
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutMissionAside",
      title: "About mission aside label",
      type: "string",
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutProcessAside",
      title: "About process aside label",
      type: "string",
      fieldset: "aboutContent",
    }),
    defineField({
      name: "studioVisualImage",
      title: "ABOUT - Gambar studio visual",
      type: "image",
      options: { hotspot: true },
      fieldset: "studioVisual",
    }),
    defineField({
      name: "servicesPageLabel",
      title: "Services page eyebrow label",
      type: "string",
      fieldset: "servicesContent",
    }),
    defineField({
      name: "servicesPageHeading",
      title: "Services page heading",
      type: "text",
      rows: 3,
      fieldset: "servicesContent",
    }),
    defineField({
      name: "servicesPageDescription",
      title: "Services page introduction",
      type: "text",
      rows: 3,
      fieldset: "servicesContent",
    }),
    defineField({
      name: "servicesProcessLabel",
      title: "Services process label",
      type: "string",
      fieldset: "servicesContent",
    }),
    defineField({
      name: "servicesProcessHeading",
      title: "Services process heading",
      type: "text",
      rows: 3,
      fieldset: "servicesContent",
    }),
    defineField({
      name: "servicesProcessDescription",
      title: "Services process introduction",
      type: "text",
      rows: 4,
      fieldset: "servicesContent",
    }),
    defineField({
      name: "servicesProcess",
      title: "Services process stages",
      type: "array",
      of: [{
        type: "object",
        fields: [
          defineField({ name: "title", title: "Stage title", type: "string" }),
          defineField({ name: "description", title: "Stage description", type: "text" }),
          defineField({ name: "image", title: "Stage image", type: "image", options: { hotspot: true } }),
          defineField({ name: "order", title: "Display order", type: "number" }),
        ],
        preview: { select: { title: "title", subtitle: "description" } },
      }],
      fieldset: "servicesContent",
    }),
    defineField({
      name: "studioVisualVideo",
      title: "ABOUT - Video studio visual",
      type: "mux.video",
      fieldset: "studioVisual",
    }),
    defineField({
      name: "officeAddress",
      title: "GLOBAL - Alamat kantor",
      type: "text",
      initialValue: "Sovereign Plaza 12th Floor - Jl. TB Simatupang No.36, Cilandak, Jakarta 12430",
      fieldset: "globalContact",
    }),
    defineField({
      name: "googleMapsUrl",
      title: "GLOBAL - Link Google Maps",
      type: "url",
      fieldset: "globalContact",
    }),
    defineField({
      name: "whatsappNumber",
      title: "GLOBAL - Nomor WhatsApp",
      type: "string",
      description: "Use the full WhatsApp number or link destination.",
      fieldset: "globalContact",
    }),
    defineField({
      name: "whatsappCtaText",
      title: "GLOBAL - Teks tombol WhatsApp",
      type: "string",
      fieldset: "globalContact",
    }),
    defineField({
      name: "aboutCtaHeading",
      title: "ABOUT - Judul CTA penutup",
      type: "string",
      fieldset: "aboutContent",
    }),
    defineField({
      name: "socialLinks",
      title: "Social media links shown in the footer",
      type: "array",
      of: [{ type: "socialLink" }],
      fieldset: "globalFooter",
    }),
    defineField({
      name: "seoDefaults",
      title: "Default SEO",
      type: "object",
      fields: [
        defineField({ name: "title", title: "Title", type: "string" }),
        defineField({ name: "description", title: "Description", type: "text" }),
      ],
      fieldset: "globalSeo",
    }),
  ],
  preview: {
    select: {
      title: "brandStatement",
    },
  },
});
