import { defineField, defineType } from "sanity";

export const siteSettings = defineType({
  name: "siteSettings",
  title: "Site settings",
  type: "document",
  fieldsets: [
    {
      name: "homeContent",
      title: "HOME - Teks & highlight",
      description: "Edit teks bagian Home dan pilih project yang tampil sebagai highlight.",
    },
    {
      name: "aboutContent",
      title: "ABOUT - Teks halaman",
      description: "Edit intro, principles, vision, mission, dan process pada halaman About.",
    },
    {
      name: "servicesContent",
      title: "SERVICES - Teks & process",
      description: "Edit intro Services, daftar layanan, dan tahapan proses kerja.",
    },
    {
      name: "studioVisual",
      title: "ABOUT - Studio visual",
      description: "Media studio yang tampil pada bagian visual halaman About. Video diprioritaskan jika keduanya diisi.",
    },
    {
      name: "globalContent",
      title: "GLOBAL - Kontak, footer & SEO",
      description: "Informasi yang dipakai bersama oleh footer, tombol kontak, sosial media, dan SEO.",
    },
  ],
  fields: [
    defineField({
      name: "logo",
      title: "GLOBAL - Logo",
      type: "image",
      options: { hotspot: true },
      fieldset: "globalContent",
    }),
    defineField({
      name: "projectHighlightImages",
      title: "SERVICES - Gambar project highlight",
      type: "array",
      of: [{ type: "image", options: { hotspot: true } }],
      validation: (Rule) => Rule.max(4),
      description: "Opsional. Gambar carousel project pada halaman Services. Maksimal 4 gambar.",
      fieldset: "servicesContent",
    }),
    defineField({
      name: "homeHighlightsLabel",
      title: "HOME - Label bagian highlight",
      type: "string",
      fieldset: "homeContent",
    }),
    defineField({
      name: "homeHighlightsTitle",
      title: "HOME - Judul bagian highlight",
      type: "string",
      fieldset: "homeContent",
    }),
    defineField({
      name: "homeHighlightsEmpty",
      title: "HOME - Pesan saat belum ada project",
      type: "text",
      rows: 2,
      fieldset: "homeContent",
    }),
    defineField({
      name: "homeDiscoverLabel",
      title: "HOME - Label link semua project",
      type: "string",
      fieldset: "homeContent",
    }),
    defineField({
      name: "brandStatement",
      title: "GLOBAL - Nama / brand statement footer",
      type: "string",
      fieldset: "globalContent",
    }),
    defineField({
      name: "aboutEstablished",
      title: "ABOUT - Tagline established",
      type: "string",
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutDescription",
      title: "ABOUT - Deskripsi studio",
      type: "text",
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutKey",
      title: "ABOUT - Kata kunci studio",
      type: "array",
      of: [{
        type: "object",
        fields: [
          defineField({ name: "label", title: "Keyword", type: "string" }),
          defineField({ name: "order", title: "Display order", type: "number" }),
        ],
      }],
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutPrinciplesIntro",
      title: "ABOUT - Intro principles",
      type: "text",
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutPrinciplesContext",
      title: "ABOUT - Catatan context principles",
      type: "text",
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutPrinciples",
      title: "ABOUT - Daftar principles",
      type: "array",
      of: [{
        type: "object",
        fields: [
          defineField({ name: "title", title: "Title", type: "string" }),
          defineField({ name: "description", title: "Description", type: "text" }),
          defineField({ name: "image", title: "Image", type: "image", options: { hotspot: true } }),
          defineField({ name: "order", title: "Display order", type: "number" }),
        ],
      }],
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutVision",
      title: "ABOUT - Teks vision",
      type: "text",
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutVisionSupport",
      title: "ABOUT - Teks pendukung vision",
      type: "text",
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutVisionImage",
      title: "ABOUT - Gambar vision",
      type: "image",
      options: { hotspot: true },
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutMission",
      title: "ABOUT - Mission points",
      type: "array",
      of: [{ type: "text" }],
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutMissionLead",
      title: "ABOUT - Mission lead",
      type: "text",
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutMissionSupport",
      title: "ABOUT - Teks pendukung mission",
      type: "text",
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutMissionDetails",
      title: "ABOUT - Detail mission",
      type: "array",
      of: [{
        type: "object",
        fields: [
          defineField({ name: "label", title: "Label", type: "string" }),
          defineField({ name: "description", title: "Description", type: "text" }),
          defineField({ name: "order", title: "Display order", type: "number" }),
        ],
      }],
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutMissionImage",
      title: "ABOUT - Gambar mission",
      type: "image",
      options: { hotspot: true },
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutProcess",
      title: "ABOUT - Tahapan process",
      type: "array",
      of: [{
        type: "object",
        fields: [
          defineField({ name: "title", title: "Stage title", type: "string" }),
          defineField({ name: "subtitle", title: "Stage subtitle", type: "string" }),
          defineField({ name: "description", title: "Stage description", type: "text" }),
          defineField({ name: "image", title: "Stage image", type: "image", options: { hotspot: true } }),
          defineField({ name: "order", title: "Display order", type: "number" }),
        ],
      }],
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutPageLabel",
      title: "About page eyebrow label",
      type: "string",
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutPrinciplesLabel",
      title: "About principles label",
      type: "string",
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutVisionLabel",
      title: "About vision label",
      type: "string",
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutMissionLabel",
      title: "About mission label",
      type: "string",
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutProcessLabel",
      title: "About process label",
      type: "string",
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutPrinciplesAside",
      title: "About principles aside label",
      type: "string",
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutVisionAside",
      title: "About vision aside label",
      type: "string",
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutMissionAside",
      title: "About mission aside label",
      type: "string",
      fieldset: "aboutContent",
    }),
    defineField({
      name: "aboutProcessAside",
      title: "About process aside label",
      type: "string",
      fieldset: "aboutContent",
    }),
    defineField({
      name: "studioVisualImage",
      title: "ABOUT - Gambar studio visual",
      type: "image",
      options: { hotspot: true },
      fieldset: "studioVisual",
    }),
    defineField({
      name: "servicesPageLabel",
      title: "Services page eyebrow label",
      type: "string",
      fieldset: "servicesContent",
    }),
    defineField({
      name: "servicesPageHeading",
      title: "Services page heading",
      type: "text",
      rows: 3,
      fieldset: "servicesContent",
    }),
    defineField({
      name: "servicesPageDescription",
      title: "Services page introduction",
      type: "text",
      rows: 3,
      fieldset: "servicesContent",
    }),
    defineField({
      name: "servicesProcessLabel",
      title: "Services process label",
      type: "string",
      fieldset: "servicesContent",
    }),
    defineField({
      name: "servicesProcessHeading",
      title: "Services process heading",
      type: "text",
      rows: 3,
      fieldset: "servicesContent",
    }),
    defineField({
      name: "servicesProcessDescription",
      title: "Services process introduction",
      type: "text",
      rows: 4,
      fieldset: "servicesContent",
    }),
    defineField({
      name: "servicesProcess",
      title: "Services process stages",
      type: "array",
      of: [{
        type: "object",
        fields: [
          defineField({ name: "title", title: "Stage title", type: "string" }),
          defineField({ name: "description", title: "Stage description", type: "text" }),
          defineField({ name: "image", title: "Stage image", type: "image", options: { hotspot: true } }),
          defineField({ name: "order", title: "Display order", type: "number" }),
        ],
        preview: { select: { title: "title", subtitle: "description" } },
      }],
      fieldset: "servicesContent",
    }),
    defineField({
      name: "studioVisualVideo",
      title: "ABOUT - Video studio visual",
      type: "mux.video",
      fieldset: "studioVisual",
    }),
    defineField({
      name: "officeAddress",
      title: "GLOBAL - Alamat kantor",
      type: "text",
      initialValue: "Sovereign Plaza 12th Floor - Jl. TB Simatupang No.36, Cilandak, Jakarta 12430",
      fieldset: "globalContent",
    }),
    defineField({
      name: "googleMapsUrl",
      title: "GLOBAL - Link Google Maps",
      type: "url",
      fieldset: "globalContent",
    }),
    defineField({
      name: "whatsappNumber",
      title: "GLOBAL - Nomor WhatsApp",
      type: "string",
      description: "Use the full WhatsApp number or link destination.",
      fieldset: "globalContent",
    }),
    defineField({
      name: "whatsappCtaText",
      title: "GLOBAL - Teks tombol WhatsApp",
      type: "string",
      fieldset: "globalContent",
    }),
    defineField({
      name: "aboutCtaHeading",
      title: "ABOUT - Judul CTA penutup",
      type: "string",
      fieldset: "aboutContent",
    }),
    defineField({
      name: "socialLinks",
      title: "GLOBAL - Social media links",
      type: "array",
      of: [{ type: "socialLink" }],
      fieldset: "globalContent",
    }),
    defineField({
      name: "seoDefaults",
      title: "GLOBAL - SEO default",
      type: "object",
      fields: [
        defineField({ name: "title", title: "Title", type: "string" }),
        defineField({ name: "description", title: "Description", type: "text" }),
      ],
      fieldset: "globalContent",
    }),
  ],
  preview: {
    select: {
      title: "brandStatement",
    },
  },
});
